versions:
  checkers:
    TICSpp:
        version: 47193
        platform: linux64
    eslint:
        version: 47124
        platform: x64
    pmd:
        version: 47503
  rules:
  ticsbin:
    # TICS binaries can be downloaded from 'https://portal.tiobe.com/downloads/files/pub/releases'.
    # Look for the 'Latest binary artifact snapshots' for your platform.
    # Place the downloaded binaries in the 'bin' folder and update the path to the artifact below accordingly.
    artifact: /bin/tics-bin-2022.2.1.47532-ubuntu_16.04.zip
